output_dir: ~/git/ultra_torchdrug/ultra_output/

dataset:
  class: {{ dataset }}
  path: ~/git/ultra_torchdrug/kg-datasets/

task:
  class: KnowledgeGraphCompletionAdapted
  model:
    class: TransferNBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
    project: yes
    mod: yes
    remove_one_hop: no
  rel_models:
    class: RelationModelList
    num_rel_models: 1
    rel_model:
      class_str: RelNBFNet
      input_dim: 64
      input_type: ones 
      num_layers: 6
      num_heads: 4
      hidden: 64
      dropout_rate: 0.1
      mine_complexes: no
      output_layer_norm: no
      remove_self_loops: no
  criterion: bce
  num_negative: 128
  strict_negative: yes
  adversarial_temperature: 1.0
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: AdamW
  lr: 0.0005

engine:
  gpus: {{ gpus }}
  batch_size: 16

train:
  num_epoch: {{ epochs }}
  batch_per_epoch: {{ bpe }}

debug: no  
metric: mrr
checkpoint: {{ ckpt }} 
